<?php

/**
 * @file
 * Renders Administration menu like Toolbar (core) module.
 *
 * @todo Separate shortcut functionality into own module/widget.
 */

/**
 * Implementation of hook_page_build().
 */
function admin_menu_toolbar_page_build(&$page) {
  if (!isset($page['page_bottom']['admin_menu'])) {
    return;
  }
  $path = drupal_get_path('module', 'admin_menu_toolbar');
  $attached = &$page['page_bottom']['admin_menu']['#attached'];

  $attached['css'][] = $path . '/admin_menu_toolbar.css';
  $attached['js'][] = $path . '/admin_menu_toolbar.js';

  $settings = array();
  // Add current path to support menu item highlighting.
  // @todo Compile real active trail here?
  $args = explode('/', $_GET['q']);
  if ($args[0] == 'admin' && !empty($args[1])) {
    $settings['activeTrail'] = url($args[0] . '/' . $args[1]);
  }
  elseif (drupal_is_front_page()) {
    $settings['activeTrail'] = url('<front>');
  }

  $attached['js'][] = array(
    'data' => array('admin_menu' => array('toolbar' => $settings)),
    'type' => 'setting',
  );
}

/**
 * Implements hook_admin_menu_output_build().
 */
function admin_menu_toolbar_admin_menu_output_build(&$content) {
  // Add shortcuts menu.
  $content['shortcuts'] = array(
    '#theme' => 'admin_menu_links',
    '#weight' => -200,
  );
  $content['shortcuts']['shortcuts'] = array(
    '#title' => t('Show shortcuts'),
    // @todo How do we want to trigger/store state?
    '#attributes' => array('class' => array('admin-menu-shortcuts')),
    //'#attributes' => array('class' => array('admin-menu-shortcuts', 'admin-menu-shortcuts-active')),
    '#options' => array(
      'attributes' => array('class' => 'toggle'),
    ),
  );
  // @todo Copy this from $content['menu'] instead.
  $content['shortcuts']['shortcuts']['node-add'] = array(
    '#title' => t('Add content'),
    '#href' => 'node/add',
  );
  $content['shortcuts']['shortcuts']['admin-content-node'] = array(
    '#title' => t('Find content'),
    '#href' => 'admin/content/node',
    '#access' => user_access('administer nodes'),
  );
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function admin_menu_toolbar_admin_menu_output_alter(&$content) {
  // Add a class to top-level items for styling.
  foreach (element_children($content['menu']) as $link) {
    $content['menu'][$link]['#attributes']['class'][] = 'admin-menu-toolbar-category';
  }

  // Alter icon.
  unset($content['icon']['icon']['#theme']);
  $content['icon']['icon']['#title'] = '<span>' . t('Home') . '</span>';
  $content['icon']['icon']['#attributes']['class'][] = 'admin-menu-toolbar-category';

  // Alter user account link.
  $content['user']['account']['#title'] = t('Hello <strong>@username</strong>', array('@username' => $content['user']['account']['#title']));
  $content['user']['account']['#options']['html'] = TRUE;
}

