<?php

/**
 * @file
 * Utility module for Occupy Directory.
 */

/**
 * Implements hook_help().
 */
function directory_help($path, $arg) {
  if ($path == 'admin/help#directory') {
    return t('Help for the directory module!');
  }
}

/**
 * Implements hook_block_info().
 */
function directory_block_info() {
  $blocks = array();
  $blocks['directory-map'] = array(
    'info' => t('The directory map as a block template.'),
    // 'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_theme().
 *
 * Defines default theme template for a list of tweets.
 */
function directory_theme() {
  $ret = array(
    'directory-map' => array(
      'template' => 'directory_map',
    ),
  );
  watchdog( 'directory', $ret );
  return $ret;
}

/**
 * Implements hook_block_view().
 */
function directory_block_view( $delta = '') {
  switch( $delta ){
    case 'directory-map':
      drupal_add_js(drupal_get_path('module', 'directory') . '/js/directory.js');
//    $block['subject'] = t('Directory Map');
      $block['content'] = theme('directory-map'); 
      return $block;
    break;
 }
}