<?php

/**
 * @file
 * Utility module for Occupy Directory.
 */

/**
 * Implements hook_help().
 */
function directory_help($path, $arg) {
  if ($path == 'admin/help#directory') {
    return t('Help for the directory module!');
  }
}

/**
 * Implements hook_block_info().
 */
function directory_block_info() {
  $blocks = array();
  $blocks['directory-map'] = array(
    'info' => t('The directory map as a block template pulling in the directory embed via iframe.'),
  );
  $blocks['directory-map-experimental'] = array(
    'info' => t('The directory map included natively in page'),
  );
  return $blocks;
}

/**
 * Implements hook_theme().
 *
 * Defines default theme template for a list of tweets.
 */
function directory_theme() {
  $ret = array(
    'directory-map' => array(
      'template' => 'directory_map',
    ),
    'directory-map-experimental' => array(
      'template' => 'directory_map_experimental',
    ),
  );
  return $ret;
}

/**
 * Implements hook_block_view().
 */
function directory_block_view( $delta = '') {
  switch( $delta ){
    case 'directory-map':
      drupal_add_js(drupal_get_path('module', 'directory') . '/js/directory_map.js');
      $block['content'] = theme('directory-map'); 
      return $block;
    break;
    case 'directory-map-experimental':
      // todo: add the map-specific css here
      drupal_add_js(drupal_get_path('module', 'directory') . '/js/directory_map_experimental.js');
      drupal_add_js( 'http://api.tiles.mapbox.com/mapbox.js/v0.6.3/mapbox.js' );
      $block['content'] = theme('directory-map-experimental'); 
      return $block;
    break;
 }
}