<?php
/**
 * @file
 * directory_solr.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function directory_solr_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  list($module, $api) = func_get_args();
  if ($module == "facetapi" && $api == "facetapi_defaults") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function directory_solr_views_api() {
  return array("version" => "3.0");
}
